In [2]:
import torch

# Tensors

In [5]:
a = torch.tensor([1,2,2])
print(a)

tensor([1, 2, 2])


In [10]:
b = torch.tensor([[1,2,2],[3,4,5],[9,9,9],[1,1,1]])
print(b)

tensor([[1, 2, 2],
        [3, 4, 5],
        [9, 9, 9],
        [1, 1, 1]])


In [11]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [14]:
print(b.shape[0])

4


# NUMPY

In [2]:
import numpy as np

In [6]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [9]:
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
        a.cuda()
        print(a)

False


# DIMENSIONS

In [4]:
tensor_1 = torch.tensor([1,2,3,4])
tensor_a = torch.unsqueeze(tensor_1, 0)

print(tensor_a)
print(tensor_a.shape)

tensor_b = torch.unsqueeze(tensor_1,1)

print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


# 